services:
  - type: web
    name: flet-app
    env:
      - API_KEY: ${{ secrets.API_KEY }}
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: FLET_RUNTIME
        value: "web"

