services:
  - type: web
    name: flet-app
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: FLET_RUNTIME
        value: "web"
      - key: API_KEY
        fromEnvVar: API_KEY

