services:
  - type: web
    name: flet-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: "app: uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /
    
